modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Vazkii/Patchouli"

[[mods]]
modId="patchouli"
displayName="Patchouli"
version="${version}"
authors="Vazkii"
description='''
Accessible, Data-Driven, Dependency-Free Documentation for Minecraft Modders and Pack Makers
'''

[[dependencies.patchouli]]
    modId="forge"
    mandatory=true
    versionRange="[28.0.49,)"
